fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    file_concat: "https://github.com/electrical/puppet-lib-file_concat.git"
  symlinks:
    ezproxy: "#{source_dir}"
